title: Hu Zhenyu's Blog
description: My Personal Blog
author: Hu Zhenyu 
logo: /static/img/avatar.png
github: https://github.com/andyhuzhill
about: C++ Programmer 
permalink: /:categories/:year/:month/:day/:title 

baseurl: ""
url: ""

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge

markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge

allowsearch: true

disqus_shortname: andylinux
google_analytics: UA-123-12

share:
  twitter_username: andyscout2

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
gems: [jekyll-paginate, jekyll-gist]
